# ServiceNow Ticket Automation Configuration

# Fallback settings for when dynamic lookups fail
servicenow_fallbacks:
  default_caller:
    sys_id: ""  # Leave empty to skip caller assignment
    name: "Unknown Caller"
    email: "unknown@company.com"
  
  default_assignment_group:
    sys_id: ""  # Leave empty to use fallback name lookup
    name: "General Support"

# Available incident categories and their descriptions
incident_categories:
  IT:
    description: "Information Technology related issues"
    subcategories:
      - "Software"
      - "Hardware" 
      - "Network"
      - "Access Management"
      - "Database"
      - "System Performance"
  
  HR:
    description: "Human Resources matters"
    subcategories:
      - "Benefits"
      - "Payroll"
      - "Policies"
      - "Onboarding"
      - "Offboarding" 
      - "Training"
  
  Finance:
    description: "Financial and accounting issues"
    subcategories:
      - "Invoices"
      - "Expenses"
      - "Budget"
      - "Payments"
      - "Purchase Orders"
      - "Reimbursements"
  
  Facilities:
    description: "Office and facilities management"
    subcategories:
      - "Maintenance"
      - "Access Control"
      - "Equipment"
      - "Space Management"
      - "Security"
      - "Utilities"
  
  General:
    description: "General support requests"
    subcategories:
      - "Information Request"
      - "Other"

# Mapping of categories to ServiceNow assignment groups
category_to_group:
  IT: "IT Support Team"
  HR: "Human Resources"
  Finance: "Finance Team"
  Facilities: "Facilities Management"
  General: "General Support"

# Mapping of categories to specific users (optional)
category_to_user:
  IT: ""  # Leave empty for group assignment only
  HR: ""
  Finance: ""
  Facilities: ""
  General: ""

# ServiceNow category field mapping
servicenow_category_mapping:
  IT: "Software"
  HR: "Human Resources"
  Finance: "Finance"  
  Facilities: "Facilities"
  General: "General"

# Email notification templates
email_templates:
  ticket_created:
    subject: "Support Ticket Created - {ticket_number}"
    body: |
      Dear {caller_name},

      Your support request has been received and a ticket has been created.

      Ticket Details:
      - Ticket Number: {ticket_number}
      - Subject: {short_description}
      - Priority: {priority}
      - Assigned to: {assigned_group}

      Description:
      {description}

      You will receive updates as your ticket is processed. If you have any additional 
      information or questions, please reply to this email and reference your ticket number.

      Thank you,
      {from_name}

      ---
      This is an automated message. Please do not reply directly to this email.
      Ticket ID: {ticket_number}
      Created: {created_time}

  ticket_closed:
    subject: "Support Ticket Resolved - {ticket_number}"
    body: |
      Dear {caller_name},

      Your support ticket has been resolved and closed.

      Ticket Details:
      - Ticket Number: {ticket_number}
      - Subject: {short_description}
      - Resolution: {resolution_notes}
      - Closed: {closed_time}

      If you are satisfied with the resolution, no further action is required. 
      If you need additional assistance or if the issue persists, please create 
      a new support request.

      Thank you for using our support services.

      Best regards,
      {from_name}

      ---
      This is an automated message.
      Ticket ID: {ticket_number}
      Resolved: {closed_time}

  ticket_updated:
      subject: "Support Ticket Updated - {ticket_number} - {status}"
      body: |
        Dear {caller_name},

        Your support ticket has been updated.

        Ticket Details:
        - Ticket Number: {ticket_number}
        - Subject: {short_description}
        - New Status: {status}
        - Last Updated: {updated_time}

        Update Details:
        {update_notes}

        You will continue to receive updates as your ticket progresses.

        Thank you,
        {from_name}

        ---
        This is an automated message.
        Ticket ID: {ticket_number}
    

# Application settings
from_name: "IT Support System"
create_unknown_users: true  # Set to true to auto-create users not found in ServiceNow
send_status_updates: true   # Set to true to send email on all status changes

# AI Processing settings
ai_settings:
  classification_confidence_threshold: 0.7
  summary_max_length: 500
  category_confidence_threshold: 0.6

# Email processing settings
email_settings:
  max_body_preview_length: 200
  ignore_auto_replies: true
  skip_delivery_reports: true
  
# Monitoring and maintenance
maintenance:
  cleanup_old_tickets_days: 30
  log_retention_days: 30
  max_tracked_tickets: 1000